name: concept_learning_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11.13
  - pip
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - pillow
  - tqdm
  - pyyaml
  - requests
  - setuptools
  - wheel
  - pip:
      - torch==2.4.1
      - torchvision==0.19.1
      - torchaudio==2.4.1
      - accelerate==1.10.1
      - attrs==25.3.0
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - click==8.2.1
      - datasets==4.0.0
      - deepspeed==0.17.5
      - einops==0.8.1
      - evaluate==0.4.5
      - gitdb==4.0.12
      - gitpython==3.1.45
      - hjson==3.1.0
      - idna==3.10
      - jinja2==3.1.4
      - joblib==1.5.2
      - markupsafe==2.1.5
      - msgpack==1.1.1
      - networkx==3.3
      - ninja==1.13.0
      - packaging==25.0
      - platformdirs==4.4.0
      - protobuf==6.32.0
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - pyarrow==21.0.0
      - pydantic==2.11.7
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - sentry-sdk==2.36.0
      - six==1.17.0
      - smmap==5.0.2
      - threadpoolctl==3.6.0
      - triton==3.0.0
      - typing-extensions==4.12.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - wandb==0.21.3